---
- include_tasks: variables.yml
- include_tasks: packages.yml

- name: ensure the Certbot configuration directory exists
  file:
    path: "{{ dubzland_certbot_rfc2136_configuration_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: ensure the deploy-hook is configured
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    regexp: '^deploy-hook'
    line: "deploy-hook = {{ dubzland_certbot_rfc2136_deploy_hook }}"
    owner: root
    group: root
    mode: 0644
    state: present
  when: dubzland_certbot_rfc2136_deploy_hook is defined

- name: ensure Certbot configuration files are present for certificates
  template:
    src: etc/certbot/certificate.ini.j2
    # yamllint disable-line rule:line-length
    dest: "{{ dubzland_certbot_rfc2136_configuration_directory }}/{{ item.name }}.ini"
    owner: root
    group: root
    mode: 0600
  with_items: "{{ dubzland_certbot_rfc2136_certs }}"

- name: dump the Certbot commands
  debug:
    # yamllint disable-line rule:line-length
    msg: "{{ lookup('template', 'lookups/_certbot_command.j2', convert_data=False) | from_yaml }}"
  with_items: "{{ dubzland_certbot_rfc2136_certs }}"
  when: dubzland_certbot_rfc2136_testing is defined

- name: ensure Certbot certificates exist
  # yamllint disable-line rule:line-length
  command: "{{ lookup('template', 'lookups/_certbot_command.j2', convert_data=False) | from_yaml }}"
  args:
    creates: /etc/letsencrypt/live/{{ item.name }}/fullchain.pem
  with_items: "{{ dubzland_certbot_rfc2136_certs }}"
  when: dubzland_certbot_rfc2136_testing is not defined
