---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-certbot-rfc2136
      vars:
        dubzland_certbot_rfc2136_certs:
          - name: example_com
            email: joeschmoe@example.com
            dns_server: 10.0.1.1
            dns_port: 53
            domains:
              - '*.example.com'
              - 'example.com'
            rfc2136_key:
              name: example_com_wildcard.
              algorithm: HMAC-SHA256
              secret: 27336a3302df310d7abd2ed04e9713aef236f610d2a2327b0e0b668c788ba2f397d2431b8b745560b5a4a80aa9df52919b0cf1852cbcb73e1e69aa7d41319caf
        dubzland_certbot_rfc2136_dry_run: True
        dubzland_certbot_rfc2136_testing: True
